// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/restcol/api/go-openapiv2/models"
)

// RestColServiceQueryDocumentReader is a Reader for the RestColServiceQueryDocument structure.
type RestColServiceQueryDocumentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestColServiceQueryDocumentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRestColServiceQueryDocumentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRestColServiceQueryDocumentDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRestColServiceQueryDocumentOK creates a RestColServiceQueryDocumentOK with default headers values
func NewRestColServiceQueryDocumentOK() *RestColServiceQueryDocumentOK {
	return &RestColServiceQueryDocumentOK{}
}

/*
RestColServiceQueryDocumentOK describes a response with status code 200, with default header values.

A successful response.
*/
type RestColServiceQueryDocumentOK struct {
	Payload *models.APIQueryDocumentResponse
}

// IsSuccess returns true when this rest col service query document o k response has a 2xx status code
func (o *RestColServiceQueryDocumentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rest col service query document o k response has a 3xx status code
func (o *RestColServiceQueryDocumentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rest col service query document o k response has a 4xx status code
func (o *RestColServiceQueryDocumentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rest col service query document o k response has a 5xx status code
func (o *RestColServiceQueryDocumentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this rest col service query document o k response a status code equal to that given
func (o *RestColServiceQueryDocumentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rest col service query document o k response
func (o *RestColServiceQueryDocumentOK) Code() int {
	return 200
}

func (o *RestColServiceQueryDocumentOK) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/collections/{collectionId}/docs][%d] restColServiceQueryDocumentOK  %+v", 200, o.Payload)
}

func (o *RestColServiceQueryDocumentOK) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/collections/{collectionId}/docs][%d] restColServiceQueryDocumentOK  %+v", 200, o.Payload)
}

func (o *RestColServiceQueryDocumentOK) GetPayload() *models.APIQueryDocumentResponse {
	return o.Payload
}

func (o *RestColServiceQueryDocumentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIQueryDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestColServiceQueryDocumentDefault creates a RestColServiceQueryDocumentDefault with default headers values
func NewRestColServiceQueryDocumentDefault(code int) *RestColServiceQueryDocumentDefault {
	return &RestColServiceQueryDocumentDefault{
		_statusCode: code,
	}
}

/*
RestColServiceQueryDocumentDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RestColServiceQueryDocumentDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this rest col service query document default response has a 2xx status code
func (o *RestColServiceQueryDocumentDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this rest col service query document default response has a 3xx status code
func (o *RestColServiceQueryDocumentDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this rest col service query document default response has a 4xx status code
func (o *RestColServiceQueryDocumentDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this rest col service query document default response has a 5xx status code
func (o *RestColServiceQueryDocumentDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this rest col service query document default response a status code equal to that given
func (o *RestColServiceQueryDocumentDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the rest col service query document default response
func (o *RestColServiceQueryDocumentDefault) Code() int {
	return o._statusCode
}

func (o *RestColServiceQueryDocumentDefault) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/collections/{collectionId}/docs][%d] RestColService_QueryDocument default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceQueryDocumentDefault) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/collections/{collectionId}/docs][%d] RestColService_QueryDocument default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceQueryDocumentDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RestColServiceQueryDocumentDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
