// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/restcol/api/go-openapiv2/models"
)

// RestColServiceCreateDocumentReader is a Reader for the RestColServiceCreateDocument structure.
type RestColServiceCreateDocumentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestColServiceCreateDocumentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRestColServiceCreateDocumentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRestColServiceCreateDocumentDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRestColServiceCreateDocumentOK creates a RestColServiceCreateDocumentOK with default headers values
func NewRestColServiceCreateDocumentOK() *RestColServiceCreateDocumentOK {
	return &RestColServiceCreateDocumentOK{}
}

/*
RestColServiceCreateDocumentOK describes a response with status code 200, with default header values.

A successful response.
*/
type RestColServiceCreateDocumentOK struct {
	Payload *models.APICreateDocumentResponse
}

// IsSuccess returns true when this rest col service create document o k response has a 2xx status code
func (o *RestColServiceCreateDocumentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rest col service create document o k response has a 3xx status code
func (o *RestColServiceCreateDocumentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rest col service create document o k response has a 4xx status code
func (o *RestColServiceCreateDocumentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rest col service create document o k response has a 5xx status code
func (o *RestColServiceCreateDocumentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this rest col service create document o k response a status code equal to that given
func (o *RestColServiceCreateDocumentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rest col service create document o k response
func (o *RestColServiceCreateDocumentOK) Code() int {
	return 200
}

func (o *RestColServiceCreateDocumentOK) Error() string {
	return fmt.Sprintf("[POST /v1/newdoc][%d] restColServiceCreateDocumentOK  %+v", 200, o.Payload)
}

func (o *RestColServiceCreateDocumentOK) String() string {
	return fmt.Sprintf("[POST /v1/newdoc][%d] restColServiceCreateDocumentOK  %+v", 200, o.Payload)
}

func (o *RestColServiceCreateDocumentOK) GetPayload() *models.APICreateDocumentResponse {
	return o.Payload
}

func (o *RestColServiceCreateDocumentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APICreateDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestColServiceCreateDocumentDefault creates a RestColServiceCreateDocumentDefault with default headers values
func NewRestColServiceCreateDocumentDefault(code int) *RestColServiceCreateDocumentDefault {
	return &RestColServiceCreateDocumentDefault{
		_statusCode: code,
	}
}

/*
RestColServiceCreateDocumentDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RestColServiceCreateDocumentDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this rest col service create document default response has a 2xx status code
func (o *RestColServiceCreateDocumentDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this rest col service create document default response has a 3xx status code
func (o *RestColServiceCreateDocumentDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this rest col service create document default response has a 4xx status code
func (o *RestColServiceCreateDocumentDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this rest col service create document default response has a 5xx status code
func (o *RestColServiceCreateDocumentDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this rest col service create document default response a status code equal to that given
func (o *RestColServiceCreateDocumentDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the rest col service create document default response
func (o *RestColServiceCreateDocumentDefault) Code() int {
	return o._statusCode
}

func (o *RestColServiceCreateDocumentDefault) Error() string {
	return fmt.Sprintf("[POST /v1/newdoc][%d] RestColService_CreateDocument default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceCreateDocumentDefault) String() string {
	return fmt.Sprintf("[POST /v1/newdoc][%d] RestColService_CreateDocument default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceCreateDocumentDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RestColServiceCreateDocumentDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
