// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/restcol/api/go-openapiv2/models"
)

// NewRestColServiceCreateDocumentParams creates a new RestColServiceCreateDocumentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRestColServiceCreateDocumentParams() *RestColServiceCreateDocumentParams {
	return &RestColServiceCreateDocumentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRestColServiceCreateDocumentParamsWithTimeout creates a new RestColServiceCreateDocumentParams object
// with the ability to set a timeout on a request.
func NewRestColServiceCreateDocumentParamsWithTimeout(timeout time.Duration) *RestColServiceCreateDocumentParams {
	return &RestColServiceCreateDocumentParams{
		timeout: timeout,
	}
}

// NewRestColServiceCreateDocumentParamsWithContext creates a new RestColServiceCreateDocumentParams object
// with the ability to set a context for a request.
func NewRestColServiceCreateDocumentParamsWithContext(ctx context.Context) *RestColServiceCreateDocumentParams {
	return &RestColServiceCreateDocumentParams{
		Context: ctx,
	}
}

// NewRestColServiceCreateDocumentParamsWithHTTPClient creates a new RestColServiceCreateDocumentParams object
// with the ability to set a custom HTTPClient for a request.
func NewRestColServiceCreateDocumentParamsWithHTTPClient(client *http.Client) *RestColServiceCreateDocumentParams {
	return &RestColServiceCreateDocumentParams{
		HTTPClient: client,
	}
}

/*
RestColServiceCreateDocumentParams contains all the parameters to send to the API endpoint

	for the rest col service create document operation.

	Typically these are written to a http.Request.
*/
type RestColServiceCreateDocumentParams struct {

	// Body.
	Body *models.RestColServiceCreateDocumentBody

	// Cid.
	Cid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rest col service create document params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceCreateDocumentParams) WithDefaults() *RestColServiceCreateDocumentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rest col service create document params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceCreateDocumentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rest col service create document params
func (o *RestColServiceCreateDocumentParams) WithTimeout(timeout time.Duration) *RestColServiceCreateDocumentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rest col service create document params
func (o *RestColServiceCreateDocumentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rest col service create document params
func (o *RestColServiceCreateDocumentParams) WithContext(ctx context.Context) *RestColServiceCreateDocumentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rest col service create document params
func (o *RestColServiceCreateDocumentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rest col service create document params
func (o *RestColServiceCreateDocumentParams) WithHTTPClient(client *http.Client) *RestColServiceCreateDocumentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rest col service create document params
func (o *RestColServiceCreateDocumentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the rest col service create document params
func (o *RestColServiceCreateDocumentParams) WithBody(body *models.RestColServiceCreateDocumentBody) *RestColServiceCreateDocumentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the rest col service create document params
func (o *RestColServiceCreateDocumentParams) SetBody(body *models.RestColServiceCreateDocumentBody) {
	o.Body = body
}

// WithCid adds the cid to the rest col service create document params
func (o *RestColServiceCreateDocumentParams) WithCid(cid string) *RestColServiceCreateDocumentParams {
	o.SetCid(cid)
	return o
}

// SetCid adds the cid to the rest col service create document params
func (o *RestColServiceCreateDocumentParams) SetCid(cid string) {
	o.Cid = cid
}

// WriteToRequest writes these params to a swagger request
func (o *RestColServiceCreateDocumentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param cid
	if err := r.SetPathParam("cid", o.Cid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
