// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/restcol/api/go-openapiv2/models"
)

// RestColServiceDeleteDocumentReader is a Reader for the RestColServiceDeleteDocument structure.
type RestColServiceDeleteDocumentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestColServiceDeleteDocumentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRestColServiceDeleteDocumentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRestColServiceDeleteDocumentDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRestColServiceDeleteDocumentOK creates a RestColServiceDeleteDocumentOK with default headers values
func NewRestColServiceDeleteDocumentOK() *RestColServiceDeleteDocumentOK {
	return &RestColServiceDeleteDocumentOK{}
}

/*
RestColServiceDeleteDocumentOK describes a response with status code 200, with default header values.

A successful response.
*/
type RestColServiceDeleteDocumentOK struct {
	Payload models.APIDeleteDocumentResponse
}

// IsSuccess returns true when this rest col service delete document o k response has a 2xx status code
func (o *RestColServiceDeleteDocumentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rest col service delete document o k response has a 3xx status code
func (o *RestColServiceDeleteDocumentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rest col service delete document o k response has a 4xx status code
func (o *RestColServiceDeleteDocumentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rest col service delete document o k response has a 5xx status code
func (o *RestColServiceDeleteDocumentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this rest col service delete document o k response a status code equal to that given
func (o *RestColServiceDeleteDocumentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rest col service delete document o k response
func (o *RestColServiceDeleteDocumentOK) Code() int {
	return 200
}

func (o *RestColServiceDeleteDocumentOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/collections/{collectionId}/docs/{documentId}][%d] restColServiceDeleteDocumentOK  %+v", 200, o.Payload)
}

func (o *RestColServiceDeleteDocumentOK) String() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/collections/{collectionId}/docs/{documentId}][%d] restColServiceDeleteDocumentOK  %+v", 200, o.Payload)
}

func (o *RestColServiceDeleteDocumentOK) GetPayload() models.APIDeleteDocumentResponse {
	return o.Payload
}

func (o *RestColServiceDeleteDocumentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestColServiceDeleteDocumentDefault creates a RestColServiceDeleteDocumentDefault with default headers values
func NewRestColServiceDeleteDocumentDefault(code int) *RestColServiceDeleteDocumentDefault {
	return &RestColServiceDeleteDocumentDefault{
		_statusCode: code,
	}
}

/*
RestColServiceDeleteDocumentDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RestColServiceDeleteDocumentDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this rest col service delete document default response has a 2xx status code
func (o *RestColServiceDeleteDocumentDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this rest col service delete document default response has a 3xx status code
func (o *RestColServiceDeleteDocumentDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this rest col service delete document default response has a 4xx status code
func (o *RestColServiceDeleteDocumentDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this rest col service delete document default response has a 5xx status code
func (o *RestColServiceDeleteDocumentDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this rest col service delete document default response a status code equal to that given
func (o *RestColServiceDeleteDocumentDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the rest col service delete document default response
func (o *RestColServiceDeleteDocumentDefault) Code() int {
	return o._statusCode
}

func (o *RestColServiceDeleteDocumentDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/collections/{collectionId}/docs/{documentId}][%d] RestColService_DeleteDocument default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceDeleteDocumentDefault) String() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/collections/{collectionId}/docs/{documentId}][%d] RestColService_DeleteDocument default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceDeleteDocumentDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RestColServiceDeleteDocumentDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
