// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRestColServiceGetDocumentParams creates a new RestColServiceGetDocumentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRestColServiceGetDocumentParams() *RestColServiceGetDocumentParams {
	return &RestColServiceGetDocumentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRestColServiceGetDocumentParamsWithTimeout creates a new RestColServiceGetDocumentParams object
// with the ability to set a timeout on a request.
func NewRestColServiceGetDocumentParamsWithTimeout(timeout time.Duration) *RestColServiceGetDocumentParams {
	return &RestColServiceGetDocumentParams{
		timeout: timeout,
	}
}

// NewRestColServiceGetDocumentParamsWithContext creates a new RestColServiceGetDocumentParams object
// with the ability to set a context for a request.
func NewRestColServiceGetDocumentParamsWithContext(ctx context.Context) *RestColServiceGetDocumentParams {
	return &RestColServiceGetDocumentParams{
		Context: ctx,
	}
}

// NewRestColServiceGetDocumentParamsWithHTTPClient creates a new RestColServiceGetDocumentParams object
// with the ability to set a custom HTTPClient for a request.
func NewRestColServiceGetDocumentParamsWithHTTPClient(client *http.Client) *RestColServiceGetDocumentParams {
	return &RestColServiceGetDocumentParams{
		HTTPClient: client,
	}
}

/*
RestColServiceGetDocumentParams contains all the parameters to send to the API endpoint

	for the rest col service get document operation.

	Typically these are written to a http.Request.
*/
type RestColServiceGetDocumentParams struct {

	// CollectionID.
	CollectionID string

	// DocumentID.
	DocumentID string

	/* FieldSelectors.

	   dot-concatenated fields, ex: fielda.fieldb.fieldc
	*/
	FieldSelectors []string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rest col service get document params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceGetDocumentParams) WithDefaults() *RestColServiceGetDocumentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rest col service get document params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceGetDocumentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rest col service get document params
func (o *RestColServiceGetDocumentParams) WithTimeout(timeout time.Duration) *RestColServiceGetDocumentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rest col service get document params
func (o *RestColServiceGetDocumentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rest col service get document params
func (o *RestColServiceGetDocumentParams) WithContext(ctx context.Context) *RestColServiceGetDocumentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rest col service get document params
func (o *RestColServiceGetDocumentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rest col service get document params
func (o *RestColServiceGetDocumentParams) WithHTTPClient(client *http.Client) *RestColServiceGetDocumentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rest col service get document params
func (o *RestColServiceGetDocumentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCollectionID adds the collectionID to the rest col service get document params
func (o *RestColServiceGetDocumentParams) WithCollectionID(collectionID string) *RestColServiceGetDocumentParams {
	o.SetCollectionID(collectionID)
	return o
}

// SetCollectionID adds the collectionId to the rest col service get document params
func (o *RestColServiceGetDocumentParams) SetCollectionID(collectionID string) {
	o.CollectionID = collectionID
}

// WithDocumentID adds the documentID to the rest col service get document params
func (o *RestColServiceGetDocumentParams) WithDocumentID(documentID string) *RestColServiceGetDocumentParams {
	o.SetDocumentID(documentID)
	return o
}

// SetDocumentID adds the documentId to the rest col service get document params
func (o *RestColServiceGetDocumentParams) SetDocumentID(documentID string) {
	o.DocumentID = documentID
}

// WithFieldSelectors adds the fieldSelectors to the rest col service get document params
func (o *RestColServiceGetDocumentParams) WithFieldSelectors(fieldSelectors []string) *RestColServiceGetDocumentParams {
	o.SetFieldSelectors(fieldSelectors)
	return o
}

// SetFieldSelectors adds the fieldSelectors to the rest col service get document params
func (o *RestColServiceGetDocumentParams) SetFieldSelectors(fieldSelectors []string) {
	o.FieldSelectors = fieldSelectors
}

// WithProjectID adds the projectID to the rest col service get document params
func (o *RestColServiceGetDocumentParams) WithProjectID(projectID string) *RestColServiceGetDocumentParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the rest col service get document params
func (o *RestColServiceGetDocumentParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *RestColServiceGetDocumentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param collectionId
	if err := r.SetPathParam("collectionId", o.CollectionID); err != nil {
		return err
	}

	// path param documentId
	if err := r.SetPathParam("documentId", o.DocumentID); err != nil {
		return err
	}

	if o.FieldSelectors != nil {

		// binding items for fieldSelectors
		joinedFieldSelectors := o.bindParamFieldSelectors(reg)

		// query array param fieldSelectors
		if err := r.SetQueryParam("fieldSelectors", joinedFieldSelectors...); err != nil {
			return err
		}
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamRestColServiceGetDocument binds the parameter fieldSelectors
func (o *RestColServiceGetDocumentParams) bindParamFieldSelectors(formats strfmt.Registry) []string {
	fieldSelectorsIR := o.FieldSelectors

	var fieldSelectorsIC []string
	for _, fieldSelectorsIIR := range fieldSelectorsIR { // explode []string

		fieldSelectorsIIV := fieldSelectorsIIR // string as string
		fieldSelectorsIC = append(fieldSelectorsIC, fieldSelectorsIIV)
	}

	// items.CollectionFormat: "multi"
	fieldSelectorsIS := swag.JoinByFormat(fieldSelectorsIC, "multi")

	return fieldSelectorsIS
}
