// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/footprintai/restcol/api/go-openapiv2/models"
)

// RestColServiceQueryDocumentsStream2Reader is a Reader for the RestColServiceQueryDocumentsStream2 structure.
type RestColServiceQueryDocumentsStream2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestColServiceQueryDocumentsStream2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRestColServiceQueryDocumentsStream2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRestColServiceQueryDocumentsStream2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRestColServiceQueryDocumentsStream2OK creates a RestColServiceQueryDocumentsStream2OK with default headers values
func NewRestColServiceQueryDocumentsStream2OK() *RestColServiceQueryDocumentsStream2OK {
	return &RestColServiceQueryDocumentsStream2OK{}
}

/*
RestColServiceQueryDocumentsStream2OK describes a response with status code 200, with default header values.

A successful response.(streaming responses)
*/
type RestColServiceQueryDocumentsStream2OK struct {
	Payload *RestColServiceQueryDocumentsStream2OKBody
}

// IsSuccess returns true when this rest col service query documents stream2 o k response has a 2xx status code
func (o *RestColServiceQueryDocumentsStream2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rest col service query documents stream2 o k response has a 3xx status code
func (o *RestColServiceQueryDocumentsStream2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rest col service query documents stream2 o k response has a 4xx status code
func (o *RestColServiceQueryDocumentsStream2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rest col service query documents stream2 o k response has a 5xx status code
func (o *RestColServiceQueryDocumentsStream2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this rest col service query documents stream2 o k response a status code equal to that given
func (o *RestColServiceQueryDocumentsStream2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rest col service query documents stream2 o k response
func (o *RestColServiceQueryDocumentsStream2OK) Code() int {
	return 200
}

func (o *RestColServiceQueryDocumentsStream2OK) Error() string {
	return fmt.Sprintf("[GET /v1/collections/{collectionId}:docstream][%d] restColServiceQueryDocumentsStream2OK  %+v", 200, o.Payload)
}

func (o *RestColServiceQueryDocumentsStream2OK) String() string {
	return fmt.Sprintf("[GET /v1/collections/{collectionId}:docstream][%d] restColServiceQueryDocumentsStream2OK  %+v", 200, o.Payload)
}

func (o *RestColServiceQueryDocumentsStream2OK) GetPayload() *RestColServiceQueryDocumentsStream2OKBody {
	return o.Payload
}

func (o *RestColServiceQueryDocumentsStream2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(RestColServiceQueryDocumentsStream2OKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestColServiceQueryDocumentsStream2Default creates a RestColServiceQueryDocumentsStream2Default with default headers values
func NewRestColServiceQueryDocumentsStream2Default(code int) *RestColServiceQueryDocumentsStream2Default {
	return &RestColServiceQueryDocumentsStream2Default{
		_statusCode: code,
	}
}

/*
RestColServiceQueryDocumentsStream2Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RestColServiceQueryDocumentsStream2Default struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this rest col service query documents stream2 default response has a 2xx status code
func (o *RestColServiceQueryDocumentsStream2Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this rest col service query documents stream2 default response has a 3xx status code
func (o *RestColServiceQueryDocumentsStream2Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this rest col service query documents stream2 default response has a 4xx status code
func (o *RestColServiceQueryDocumentsStream2Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this rest col service query documents stream2 default response has a 5xx status code
func (o *RestColServiceQueryDocumentsStream2Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this rest col service query documents stream2 default response a status code equal to that given
func (o *RestColServiceQueryDocumentsStream2Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the rest col service query documents stream2 default response
func (o *RestColServiceQueryDocumentsStream2Default) Code() int {
	return o._statusCode
}

func (o *RestColServiceQueryDocumentsStream2Default) Error() string {
	return fmt.Sprintf("[GET /v1/collections/{collectionId}:docstream][%d] RestColService_QueryDocumentsStream2 default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceQueryDocumentsStream2Default) String() string {
	return fmt.Sprintf("[GET /v1/collections/{collectionId}:docstream][%d] RestColService_QueryDocumentsStream2 default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceQueryDocumentsStream2Default) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RestColServiceQueryDocumentsStream2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
RestColServiceQueryDocumentsStream2OKBody Stream result of apiGetDocumentResponse
swagger:model RestColServiceQueryDocumentsStream2OKBody
*/
type RestColServiceQueryDocumentsStream2OKBody struct {

	// error
	Error *models.RPCStatus `json:"error,omitempty"`

	// result
	Result *models.APIGetDocumentResponse `json:"result,omitempty"`
}

// Validate validates this rest col service query documents stream2 o k body
func (o *RestColServiceQueryDocumentsStream2OKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RestColServiceQueryDocumentsStream2OKBody) validateError(formats strfmt.Registry) error {
	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("restColServiceQueryDocumentsStream2OK" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("restColServiceQueryDocumentsStream2OK" + "." + "error")
			}
			return err
		}
	}

	return nil
}

func (o *RestColServiceQueryDocumentsStream2OKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("restColServiceQueryDocumentsStream2OK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("restColServiceQueryDocumentsStream2OK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this rest col service query documents stream2 o k body based on the context it is used
func (o *RestColServiceQueryDocumentsStream2OKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RestColServiceQueryDocumentsStream2OKBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {

		if swag.IsZero(o.Error) { // not required
			return nil
		}

		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("restColServiceQueryDocumentsStream2OK" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("restColServiceQueryDocumentsStream2OK" + "." + "error")
			}
			return err
		}
	}

	return nil
}

func (o *RestColServiceQueryDocumentsStream2OKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {

		if swag.IsZero(o.Result) { // not required
			return nil
		}

		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("restColServiceQueryDocumentsStream2OK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("restColServiceQueryDocumentsStream2OK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RestColServiceQueryDocumentsStream2OKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RestColServiceQueryDocumentsStream2OKBody) UnmarshalBinary(b []byte) error {
	var res RestColServiceQueryDocumentsStream2OKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
