// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRestColServiceQueryDocumentsStreamParams creates a new RestColServiceQueryDocumentsStreamParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRestColServiceQueryDocumentsStreamParams() *RestColServiceQueryDocumentsStreamParams {
	return &RestColServiceQueryDocumentsStreamParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRestColServiceQueryDocumentsStreamParamsWithTimeout creates a new RestColServiceQueryDocumentsStreamParams object
// with the ability to set a timeout on a request.
func NewRestColServiceQueryDocumentsStreamParamsWithTimeout(timeout time.Duration) *RestColServiceQueryDocumentsStreamParams {
	return &RestColServiceQueryDocumentsStreamParams{
		timeout: timeout,
	}
}

// NewRestColServiceQueryDocumentsStreamParamsWithContext creates a new RestColServiceQueryDocumentsStreamParams object
// with the ability to set a context for a request.
func NewRestColServiceQueryDocumentsStreamParamsWithContext(ctx context.Context) *RestColServiceQueryDocumentsStreamParams {
	return &RestColServiceQueryDocumentsStreamParams{
		Context: ctx,
	}
}

// NewRestColServiceQueryDocumentsStreamParamsWithHTTPClient creates a new RestColServiceQueryDocumentsStreamParams object
// with the ability to set a custom HTTPClient for a request.
func NewRestColServiceQueryDocumentsStreamParamsWithHTTPClient(client *http.Client) *RestColServiceQueryDocumentsStreamParams {
	return &RestColServiceQueryDocumentsStreamParams{
		HTTPClient: client,
	}
}

/*
RestColServiceQueryDocumentsStreamParams contains all the parameters to send to the API endpoint

	for the rest col service query documents stream operation.

	Typically these are written to a http.Request.
*/
type RestColServiceQueryDocumentsStreamParams struct {

	// CollectionID.
	CollectionID string

	/* EndedAt.

	   endedAt specifies when is the ended timeframe of the query

	   Format: date-time
	*/
	EndedAt *strfmt.DateTime

	/* FieldSelectors.

	   dot-concatenated fields, ex: fielda.fieldb.fieldc
	*/
	FieldSelectors []string

	/* FollowUpMode.

	   if on, the service would keep watch new coming docs
	*/
	FollowUpMode *bool

	// ProjectID.
	ProjectID string

	// SinceTs.
	//
	// Format: date-time
	SinceTs *strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rest col service query documents stream params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceQueryDocumentsStreamParams) WithDefaults() *RestColServiceQueryDocumentsStreamParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rest col service query documents stream params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceQueryDocumentsStreamParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) WithTimeout(timeout time.Duration) *RestColServiceQueryDocumentsStreamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) WithContext(ctx context.Context) *RestColServiceQueryDocumentsStreamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) WithHTTPClient(client *http.Client) *RestColServiceQueryDocumentsStreamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCollectionID adds the collectionID to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) WithCollectionID(collectionID string) *RestColServiceQueryDocumentsStreamParams {
	o.SetCollectionID(collectionID)
	return o
}

// SetCollectionID adds the collectionId to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) SetCollectionID(collectionID string) {
	o.CollectionID = collectionID
}

// WithEndedAt adds the endedAt to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) WithEndedAt(endedAt *strfmt.DateTime) *RestColServiceQueryDocumentsStreamParams {
	o.SetEndedAt(endedAt)
	return o
}

// SetEndedAt adds the endedAt to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) SetEndedAt(endedAt *strfmt.DateTime) {
	o.EndedAt = endedAt
}

// WithFieldSelectors adds the fieldSelectors to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) WithFieldSelectors(fieldSelectors []string) *RestColServiceQueryDocumentsStreamParams {
	o.SetFieldSelectors(fieldSelectors)
	return o
}

// SetFieldSelectors adds the fieldSelectors to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) SetFieldSelectors(fieldSelectors []string) {
	o.FieldSelectors = fieldSelectors
}

// WithFollowUpMode adds the followUpMode to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) WithFollowUpMode(followUpMode *bool) *RestColServiceQueryDocumentsStreamParams {
	o.SetFollowUpMode(followUpMode)
	return o
}

// SetFollowUpMode adds the followUpMode to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) SetFollowUpMode(followUpMode *bool) {
	o.FollowUpMode = followUpMode
}

// WithProjectID adds the projectID to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) WithProjectID(projectID string) *RestColServiceQueryDocumentsStreamParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WithSinceTs adds the sinceTs to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) WithSinceTs(sinceTs *strfmt.DateTime) *RestColServiceQueryDocumentsStreamParams {
	o.SetSinceTs(sinceTs)
	return o
}

// SetSinceTs adds the sinceTs to the rest col service query documents stream params
func (o *RestColServiceQueryDocumentsStreamParams) SetSinceTs(sinceTs *strfmt.DateTime) {
	o.SinceTs = sinceTs
}

// WriteToRequest writes these params to a swagger request
func (o *RestColServiceQueryDocumentsStreamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param collectionId
	if err := r.SetPathParam("collectionId", o.CollectionID); err != nil {
		return err
	}

	if o.EndedAt != nil {

		// query param endedAt
		var qrEndedAt strfmt.DateTime

		if o.EndedAt != nil {
			qrEndedAt = *o.EndedAt
		}
		qEndedAt := qrEndedAt.String()
		if qEndedAt != "" {

			if err := r.SetQueryParam("endedAt", qEndedAt); err != nil {
				return err
			}
		}
	}

	if o.FieldSelectors != nil {

		// binding items for fieldSelectors
		joinedFieldSelectors := o.bindParamFieldSelectors(reg)

		// query array param fieldSelectors
		if err := r.SetQueryParam("fieldSelectors", joinedFieldSelectors...); err != nil {
			return err
		}
	}

	if o.FollowUpMode != nil {

		// query param followUpMode
		var qrFollowUpMode bool

		if o.FollowUpMode != nil {
			qrFollowUpMode = *o.FollowUpMode
		}
		qFollowUpMode := swag.FormatBool(qrFollowUpMode)
		if qFollowUpMode != "" {

			if err := r.SetQueryParam("followUpMode", qFollowUpMode); err != nil {
				return err
			}
		}
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if o.SinceTs != nil {

		// query param sinceTs
		var qrSinceTs strfmt.DateTime

		if o.SinceTs != nil {
			qrSinceTs = *o.SinceTs
		}
		qSinceTs := qrSinceTs.String()
		if qSinceTs != "" {

			if err := r.SetQueryParam("sinceTs", qSinceTs); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamRestColServiceQueryDocumentsStream binds the parameter fieldSelectors
func (o *RestColServiceQueryDocumentsStreamParams) bindParamFieldSelectors(formats strfmt.Registry) []string {
	fieldSelectorsIR := o.FieldSelectors

	var fieldSelectorsIC []string
	for _, fieldSelectorsIIR := range fieldSelectorsIR { // explode []string

		fieldSelectorsIIV := fieldSelectorsIIR // string as string
		fieldSelectorsIC = append(fieldSelectorsIC, fieldSelectorsIIV)
	}

	// items.CollectionFormat: "multi"
	fieldSelectorsIS := swag.JoinByFormat(fieldSelectorsIC, "multi")

	return fieldSelectorsIS
}
