// Code generated by go-swagger; DO NOT EDIT.

package rest_col_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"footprintai/restcol/api/go-openapiv2/models"
)

// NewRestColServiceCreateDataParams creates a new RestColServiceCreateDataParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRestColServiceCreateDataParams() *RestColServiceCreateDataParams {
	return &RestColServiceCreateDataParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRestColServiceCreateDataParamsWithTimeout creates a new RestColServiceCreateDataParams object
// with the ability to set a timeout on a request.
func NewRestColServiceCreateDataParamsWithTimeout(timeout time.Duration) *RestColServiceCreateDataParams {
	return &RestColServiceCreateDataParams{
		timeout: timeout,
	}
}

// NewRestColServiceCreateDataParamsWithContext creates a new RestColServiceCreateDataParams object
// with the ability to set a context for a request.
func NewRestColServiceCreateDataParamsWithContext(ctx context.Context) *RestColServiceCreateDataParams {
	return &RestColServiceCreateDataParams{
		Context: ctx,
	}
}

// NewRestColServiceCreateDataParamsWithHTTPClient creates a new RestColServiceCreateDataParams object
// with the ability to set a custom HTTPClient for a request.
func NewRestColServiceCreateDataParamsWithHTTPClient(client *http.Client) *RestColServiceCreateDataParams {
	return &RestColServiceCreateDataParams{
		HTTPClient: client,
	}
}

/*
RestColServiceCreateDataParams contains all the parameters to send to the API endpoint

	for the rest col service create data operation.

	Typically these are written to a http.Request.
*/
type RestColServiceCreateDataParams struct {

	// Body.
	Body *models.RestColServiceCreateDataBody

	// Cid.
	Cid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rest col service create data params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceCreateDataParams) WithDefaults() *RestColServiceCreateDataParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rest col service create data params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceCreateDataParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rest col service create data params
func (o *RestColServiceCreateDataParams) WithTimeout(timeout time.Duration) *RestColServiceCreateDataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rest col service create data params
func (o *RestColServiceCreateDataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rest col service create data params
func (o *RestColServiceCreateDataParams) WithContext(ctx context.Context) *RestColServiceCreateDataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rest col service create data params
func (o *RestColServiceCreateDataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rest col service create data params
func (o *RestColServiceCreateDataParams) WithHTTPClient(client *http.Client) *RestColServiceCreateDataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rest col service create data params
func (o *RestColServiceCreateDataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the rest col service create data params
func (o *RestColServiceCreateDataParams) WithBody(body *models.RestColServiceCreateDataBody) *RestColServiceCreateDataParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the rest col service create data params
func (o *RestColServiceCreateDataParams) SetBody(body *models.RestColServiceCreateDataBody) {
	o.Body = body
}

// WithCid adds the cid to the rest col service create data params
func (o *RestColServiceCreateDataParams) WithCid(cid string) *RestColServiceCreateDataParams {
	o.SetCid(cid)
	return o
}

// SetCid adds the cid to the rest col service create data params
func (o *RestColServiceCreateDataParams) SetCid(cid string) {
	o.Cid = cid
}

// WriteToRequest writes these params to a swagger request
func (o *RestColServiceCreateDataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param cid
	if err := r.SetPathParam("cid", o.Cid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
