// Code generated by go-swagger; DO NOT EDIT.

package rest_col_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"footprintai/restcol/api/go-openapiv2/models"
)

// NewRestColServiceCreateCollectionParams creates a new RestColServiceCreateCollectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRestColServiceCreateCollectionParams() *RestColServiceCreateCollectionParams {
	return &RestColServiceCreateCollectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRestColServiceCreateCollectionParamsWithTimeout creates a new RestColServiceCreateCollectionParams object
// with the ability to set a timeout on a request.
func NewRestColServiceCreateCollectionParamsWithTimeout(timeout time.Duration) *RestColServiceCreateCollectionParams {
	return &RestColServiceCreateCollectionParams{
		timeout: timeout,
	}
}

// NewRestColServiceCreateCollectionParamsWithContext creates a new RestColServiceCreateCollectionParams object
// with the ability to set a context for a request.
func NewRestColServiceCreateCollectionParamsWithContext(ctx context.Context) *RestColServiceCreateCollectionParams {
	return &RestColServiceCreateCollectionParams{
		Context: ctx,
	}
}

// NewRestColServiceCreateCollectionParamsWithHTTPClient creates a new RestColServiceCreateCollectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewRestColServiceCreateCollectionParamsWithHTTPClient(client *http.Client) *RestColServiceCreateCollectionParams {
	return &RestColServiceCreateCollectionParams{
		HTTPClient: client,
	}
}

/*
RestColServiceCreateCollectionParams contains all the parameters to send to the API endpoint

	for the rest col service create collection operation.

	Typically these are written to a http.Request.
*/
type RestColServiceCreateCollectionParams struct {

	// Body.
	Body *models.APICreateCollectionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rest col service create collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceCreateCollectionParams) WithDefaults() *RestColServiceCreateCollectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rest col service create collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceCreateCollectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rest col service create collection params
func (o *RestColServiceCreateCollectionParams) WithTimeout(timeout time.Duration) *RestColServiceCreateCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rest col service create collection params
func (o *RestColServiceCreateCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rest col service create collection params
func (o *RestColServiceCreateCollectionParams) WithContext(ctx context.Context) *RestColServiceCreateCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rest col service create collection params
func (o *RestColServiceCreateCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rest col service create collection params
func (o *RestColServiceCreateCollectionParams) WithHTTPClient(client *http.Client) *RestColServiceCreateCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rest col service create collection params
func (o *RestColServiceCreateCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the rest col service create collection params
func (o *RestColServiceCreateCollectionParams) WithBody(body *models.APICreateCollectionRequest) *RestColServiceCreateCollectionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the rest col service create collection params
func (o *RestColServiceCreateCollectionParams) SetBody(body *models.APICreateCollectionRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RestColServiceCreateCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
