// Code generated by go-swagger; DO NOT EDIT.

package rest_col_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"footprintai/restcol/api/go-openapiv2/models"
)

// RestColServiceGetDataReader is a Reader for the RestColServiceGetData structure.
type RestColServiceGetDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestColServiceGetDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRestColServiceGetDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRestColServiceGetDataDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRestColServiceGetDataOK creates a RestColServiceGetDataOK with default headers values
func NewRestColServiceGetDataOK() *RestColServiceGetDataOK {
	return &RestColServiceGetDataOK{}
}

/*
RestColServiceGetDataOK describes a response with status code 200, with default header values.

A successful response.
*/
type RestColServiceGetDataOK struct {
	Payload models.APIGetDataResponse
}

// IsSuccess returns true when this rest col service get data o k response has a 2xx status code
func (o *RestColServiceGetDataOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rest col service get data o k response has a 3xx status code
func (o *RestColServiceGetDataOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rest col service get data o k response has a 4xx status code
func (o *RestColServiceGetDataOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rest col service get data o k response has a 5xx status code
func (o *RestColServiceGetDataOK) IsServerError() bool {
	return false
}

// IsCode returns true when this rest col service get data o k response a status code equal to that given
func (o *RestColServiceGetDataOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rest col service get data o k response
func (o *RestColServiceGetDataOK) Code() int {
	return 200
}

func (o *RestColServiceGetDataOK) Error() string {
	return fmt.Sprintf("[GET /v1/collections/{cid}/{did}][%d] restColServiceGetDataOK  %+v", 200, o.Payload)
}

func (o *RestColServiceGetDataOK) String() string {
	return fmt.Sprintf("[GET /v1/collections/{cid}/{did}][%d] restColServiceGetDataOK  %+v", 200, o.Payload)
}

func (o *RestColServiceGetDataOK) GetPayload() models.APIGetDataResponse {
	return o.Payload
}

func (o *RestColServiceGetDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestColServiceGetDataDefault creates a RestColServiceGetDataDefault with default headers values
func NewRestColServiceGetDataDefault(code int) *RestColServiceGetDataDefault {
	return &RestColServiceGetDataDefault{
		_statusCode: code,
	}
}

/*
RestColServiceGetDataDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RestColServiceGetDataDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this rest col service get data default response has a 2xx status code
func (o *RestColServiceGetDataDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this rest col service get data default response has a 3xx status code
func (o *RestColServiceGetDataDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this rest col service get data default response has a 4xx status code
func (o *RestColServiceGetDataDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this rest col service get data default response has a 5xx status code
func (o *RestColServiceGetDataDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this rest col service get data default response a status code equal to that given
func (o *RestColServiceGetDataDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the rest col service get data default response
func (o *RestColServiceGetDataDefault) Code() int {
	return o._statusCode
}

func (o *RestColServiceGetDataDefault) Error() string {
	return fmt.Sprintf("[GET /v1/collections/{cid}/{did}][%d] RestColService_GetData default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceGetDataDefault) String() string {
	return fmt.Sprintf("[GET /v1/collections/{cid}/{did}][%d] RestColService_GetData default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceGetDataDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RestColServiceGetDataDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
