// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APISchemaField api schema field
//
// swagger:model apiSchemaField
type APISchemaField struct {

	// regular sql-based datatype
	Datatype string `json:"datatype,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this api schema field
func (m *APISchemaField) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api schema field based on context it is used
func (m *APISchemaField) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APISchemaField) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APISchemaField) UnmarshalBinary(b []byte) error {
	var res APISchemaField
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
