// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APISchemaFieldExampleValue api schema field example value
//
// swagger:model apiSchemaFieldExampleValue
type APISchemaFieldExampleValue struct {

	// bool value
	BoolValue bool `json:"boolValue,omitempty"`

	// integer value
	IntegerValue string `json:"integerValue,omitempty"`

	// number value
	NumberValue float64 `json:"numberValue,omitempty"`

	// string value
	StringValue string `json:"stringValue,omitempty"`
}

// Validate validates this api schema field example value
func (m *APISchemaFieldExampleValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api schema field example value based on context it is used
func (m *APISchemaFieldExampleValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APISchemaFieldExampleValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APISchemaFieldExampleValue) UnmarshalBinary(b []byte) error {
	var res APISchemaFieldExampleValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
