// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APICreateDocumentRequest api create document request
//
// swagger:model apiCreateDocumentRequest
type APICreateDocumentRequest struct {

	// cid
	Cid string `json:"cid,omitempty"`

	// data represents rawdata for any kind of formating
	// Format: byte
	Data strfmt.Base64 `json:"data,omitempty"`

	// dataformat
	Dataformat *APIDataFormat `json:"dataformat,omitempty"`

	// did
	Did string `json:"did,omitempty"`

	// pid
	Pid string `json:"pid,omitempty"`
}

// Validate validates this api create document request
func (m *APICreateDocumentRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDataformat(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APICreateDocumentRequest) validateDataformat(formats strfmt.Registry) error {
	if swag.IsZero(m.Dataformat) { // not required
		return nil
	}

	if m.Dataformat != nil {
		if err := m.Dataformat.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dataformat")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dataformat")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this api create document request based on the context it is used
func (m *APICreateDocumentRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDataformat(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APICreateDocumentRequest) contextValidateDataformat(ctx context.Context, formats strfmt.Registry) error {

	if m.Dataformat != nil {

		if swag.IsZero(m.Dataformat) { // not required
			return nil
		}

		if err := m.Dataformat.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dataformat")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dataformat")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APICreateDocumentRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APICreateDocumentRequest) UnmarshalBinary(b []byte) error {
	var res APICreateDocumentRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
