// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRestColServiceCreateCollection2Params creates a new RestColServiceCreateCollection2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRestColServiceCreateCollection2Params() *RestColServiceCreateCollection2Params {
	return &RestColServiceCreateCollection2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewRestColServiceCreateCollection2ParamsWithTimeout creates a new RestColServiceCreateCollection2Params object
// with the ability to set a timeout on a request.
func NewRestColServiceCreateCollection2ParamsWithTimeout(timeout time.Duration) *RestColServiceCreateCollection2Params {
	return &RestColServiceCreateCollection2Params{
		timeout: timeout,
	}
}

// NewRestColServiceCreateCollection2ParamsWithContext creates a new RestColServiceCreateCollection2Params object
// with the ability to set a context for a request.
func NewRestColServiceCreateCollection2ParamsWithContext(ctx context.Context) *RestColServiceCreateCollection2Params {
	return &RestColServiceCreateCollection2Params{
		Context: ctx,
	}
}

// NewRestColServiceCreateCollection2ParamsWithHTTPClient creates a new RestColServiceCreateCollection2Params object
// with the ability to set a custom HTTPClient for a request.
func NewRestColServiceCreateCollection2ParamsWithHTTPClient(client *http.Client) *RestColServiceCreateCollection2Params {
	return &RestColServiceCreateCollection2Params{
		HTTPClient: client,
	}
}

/*
RestColServiceCreateCollection2Params contains all the parameters to send to the API endpoint

	for the rest col service create collection2 operation.

	Typically these are written to a http.Request.
*/
type RestColServiceCreateCollection2Params struct {

	// Cid.
	Cid *string

	// CollectionType.
	//
	// Default: "COLLECTION_TYPE_NONE"
	CollectionType *string

	// Description.
	Description *string

	// Pid.
	Pid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rest col service create collection2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceCreateCollection2Params) WithDefaults() *RestColServiceCreateCollection2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rest col service create collection2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceCreateCollection2Params) SetDefaults() {
	var (
		collectionTypeDefault = string("COLLECTION_TYPE_NONE")
	)

	val := RestColServiceCreateCollection2Params{
		CollectionType: &collectionTypeDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) WithTimeout(timeout time.Duration) *RestColServiceCreateCollection2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) WithContext(ctx context.Context) *RestColServiceCreateCollection2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) WithHTTPClient(client *http.Client) *RestColServiceCreateCollection2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCid adds the cid to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) WithCid(cid *string) *RestColServiceCreateCollection2Params {
	o.SetCid(cid)
	return o
}

// SetCid adds the cid to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) SetCid(cid *string) {
	o.Cid = cid
}

// WithCollectionType adds the collectionType to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) WithCollectionType(collectionType *string) *RestColServiceCreateCollection2Params {
	o.SetCollectionType(collectionType)
	return o
}

// SetCollectionType adds the collectionType to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) SetCollectionType(collectionType *string) {
	o.CollectionType = collectionType
}

// WithDescription adds the description to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) WithDescription(description *string) *RestColServiceCreateCollection2Params {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) SetDescription(description *string) {
	o.Description = description
}

// WithPid adds the pid to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) WithPid(pid string) *RestColServiceCreateCollection2Params {
	o.SetPid(pid)
	return o
}

// SetPid adds the pid to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) SetPid(pid string) {
	o.Pid = pid
}

// WriteToRequest writes these params to a swagger request
func (o *RestColServiceCreateCollection2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cid != nil {

		// query param cid
		var qrCid string

		if o.Cid != nil {
			qrCid = *o.Cid
		}
		qCid := qrCid
		if qCid != "" {

			if err := r.SetQueryParam("cid", qCid); err != nil {
				return err
			}
		}
	}

	if o.CollectionType != nil {

		// query param collectionType
		var qrCollectionType string

		if o.CollectionType != nil {
			qrCollectionType = *o.CollectionType
		}
		qCollectionType := qrCollectionType
		if qCollectionType != "" {

			if err := r.SetQueryParam("collectionType", qCollectionType); err != nil {
				return err
			}
		}
	}

	if o.Description != nil {

		// query param description
		var qrDescription string

		if o.Description != nil {
			qrDescription = *o.Description
		}
		qDescription := qrDescription
		if qDescription != "" {

			if err := r.SetQueryParam("description", qDescription); err != nil {
				return err
			}
		}
	}

	// path param pid
	if err := r.SetPathParam("pid", o.Pid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
