// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/restcol/api/go-openapiv2/models"
)

// RestColServiceDeleteCollection2Reader is a Reader for the RestColServiceDeleteCollection2 structure.
type RestColServiceDeleteCollection2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestColServiceDeleteCollection2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRestColServiceDeleteCollection2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRestColServiceDeleteCollection2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRestColServiceDeleteCollection2OK creates a RestColServiceDeleteCollection2OK with default headers values
func NewRestColServiceDeleteCollection2OK() *RestColServiceDeleteCollection2OK {
	return &RestColServiceDeleteCollection2OK{}
}

/*
RestColServiceDeleteCollection2OK describes a response with status code 200, with default header values.

A successful response.
*/
type RestColServiceDeleteCollection2OK struct {
	Payload models.APIDeleteCollectionResponse
}

// IsSuccess returns true when this rest col service delete collection2 o k response has a 2xx status code
func (o *RestColServiceDeleteCollection2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rest col service delete collection2 o k response has a 3xx status code
func (o *RestColServiceDeleteCollection2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rest col service delete collection2 o k response has a 4xx status code
func (o *RestColServiceDeleteCollection2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rest col service delete collection2 o k response has a 5xx status code
func (o *RestColServiceDeleteCollection2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this rest col service delete collection2 o k response a status code equal to that given
func (o *RestColServiceDeleteCollection2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rest col service delete collection2 o k response
func (o *RestColServiceDeleteCollection2OK) Code() int {
	return 200
}

func (o *RestColServiceDeleteCollection2OK) Error() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/collections/{collectionId}][%d] restColServiceDeleteCollection2OK  %+v", 200, o.Payload)
}

func (o *RestColServiceDeleteCollection2OK) String() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/collections/{collectionId}][%d] restColServiceDeleteCollection2OK  %+v", 200, o.Payload)
}

func (o *RestColServiceDeleteCollection2OK) GetPayload() models.APIDeleteCollectionResponse {
	return o.Payload
}

func (o *RestColServiceDeleteCollection2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestColServiceDeleteCollection2Default creates a RestColServiceDeleteCollection2Default with default headers values
func NewRestColServiceDeleteCollection2Default(code int) *RestColServiceDeleteCollection2Default {
	return &RestColServiceDeleteCollection2Default{
		_statusCode: code,
	}
}

/*
RestColServiceDeleteCollection2Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RestColServiceDeleteCollection2Default struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this rest col service delete collection2 default response has a 2xx status code
func (o *RestColServiceDeleteCollection2Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this rest col service delete collection2 default response has a 3xx status code
func (o *RestColServiceDeleteCollection2Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this rest col service delete collection2 default response has a 4xx status code
func (o *RestColServiceDeleteCollection2Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this rest col service delete collection2 default response has a 5xx status code
func (o *RestColServiceDeleteCollection2Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this rest col service delete collection2 default response a status code equal to that given
func (o *RestColServiceDeleteCollection2Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the rest col service delete collection2 default response
func (o *RestColServiceDeleteCollection2Default) Code() int {
	return o._statusCode
}

func (o *RestColServiceDeleteCollection2Default) Error() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/collections/{collectionId}][%d] RestColService_DeleteCollection2 default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceDeleteCollection2Default) String() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/collections/{collectionId}][%d] RestColService_DeleteCollection2 default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceDeleteCollection2Default) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RestColServiceDeleteCollection2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
