// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRestColServiceDeleteCollectionParams creates a new RestColServiceDeleteCollectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRestColServiceDeleteCollectionParams() *RestColServiceDeleteCollectionParams {
	return &RestColServiceDeleteCollectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRestColServiceDeleteCollectionParamsWithTimeout creates a new RestColServiceDeleteCollectionParams object
// with the ability to set a timeout on a request.
func NewRestColServiceDeleteCollectionParamsWithTimeout(timeout time.Duration) *RestColServiceDeleteCollectionParams {
	return &RestColServiceDeleteCollectionParams{
		timeout: timeout,
	}
}

// NewRestColServiceDeleteCollectionParamsWithContext creates a new RestColServiceDeleteCollectionParams object
// with the ability to set a context for a request.
func NewRestColServiceDeleteCollectionParamsWithContext(ctx context.Context) *RestColServiceDeleteCollectionParams {
	return &RestColServiceDeleteCollectionParams{
		Context: ctx,
	}
}

// NewRestColServiceDeleteCollectionParamsWithHTTPClient creates a new RestColServiceDeleteCollectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewRestColServiceDeleteCollectionParamsWithHTTPClient(client *http.Client) *RestColServiceDeleteCollectionParams {
	return &RestColServiceDeleteCollectionParams{
		HTTPClient: client,
	}
}

/*
RestColServiceDeleteCollectionParams contains all the parameters to send to the API endpoint

	for the rest col service delete collection operation.

	Typically these are written to a http.Request.
*/
type RestColServiceDeleteCollectionParams struct {

	// Cid.
	Cid string

	// Pid.
	Pid *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rest col service delete collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceDeleteCollectionParams) WithDefaults() *RestColServiceDeleteCollectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rest col service delete collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceDeleteCollectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rest col service delete collection params
func (o *RestColServiceDeleteCollectionParams) WithTimeout(timeout time.Duration) *RestColServiceDeleteCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rest col service delete collection params
func (o *RestColServiceDeleteCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rest col service delete collection params
func (o *RestColServiceDeleteCollectionParams) WithContext(ctx context.Context) *RestColServiceDeleteCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rest col service delete collection params
func (o *RestColServiceDeleteCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rest col service delete collection params
func (o *RestColServiceDeleteCollectionParams) WithHTTPClient(client *http.Client) *RestColServiceDeleteCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rest col service delete collection params
func (o *RestColServiceDeleteCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCid adds the cid to the rest col service delete collection params
func (o *RestColServiceDeleteCollectionParams) WithCid(cid string) *RestColServiceDeleteCollectionParams {
	o.SetCid(cid)
	return o
}

// SetCid adds the cid to the rest col service delete collection params
func (o *RestColServiceDeleteCollectionParams) SetCid(cid string) {
	o.Cid = cid
}

// WithPid adds the pid to the rest col service delete collection params
func (o *RestColServiceDeleteCollectionParams) WithPid(pid *string) *RestColServiceDeleteCollectionParams {
	o.SetPid(pid)
	return o
}

// SetPid adds the pid to the rest col service delete collection params
func (o *RestColServiceDeleteCollectionParams) SetPid(pid *string) {
	o.Pid = pid
}

// WriteToRequest writes these params to a swagger request
func (o *RestColServiceDeleteCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cid
	if err := r.SetPathParam("cid", o.Cid); err != nil {
		return err
	}

	if o.Pid != nil {

		// query param pid
		var qrPid string

		if o.Pid != nil {
			qrPid = *o.Pid
		}
		qPid := qrPid
		if qPid != "" {

			if err := r.SetQueryParam("pid", qPid); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
