// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/restcol/api/go-openapiv2/models"
)

// RestColServiceGetCollectionReader is a Reader for the RestColServiceGetCollection structure.
type RestColServiceGetCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestColServiceGetCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRestColServiceGetCollectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRestColServiceGetCollectionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRestColServiceGetCollectionOK creates a RestColServiceGetCollectionOK with default headers values
func NewRestColServiceGetCollectionOK() *RestColServiceGetCollectionOK {
	return &RestColServiceGetCollectionOK{}
}

/*
RestColServiceGetCollectionOK describes a response with status code 200, with default header values.

A successful response.
*/
type RestColServiceGetCollectionOK struct {
	Payload *models.APIGetCollectionResponse
}

// IsSuccess returns true when this rest col service get collection o k response has a 2xx status code
func (o *RestColServiceGetCollectionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rest col service get collection o k response has a 3xx status code
func (o *RestColServiceGetCollectionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rest col service get collection o k response has a 4xx status code
func (o *RestColServiceGetCollectionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rest col service get collection o k response has a 5xx status code
func (o *RestColServiceGetCollectionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this rest col service get collection o k response a status code equal to that given
func (o *RestColServiceGetCollectionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rest col service get collection o k response
func (o *RestColServiceGetCollectionOK) Code() int {
	return 200
}

func (o *RestColServiceGetCollectionOK) Error() string {
	return fmt.Sprintf("[GET /v1/collections/{cid}][%d] restColServiceGetCollectionOK  %+v", 200, o.Payload)
}

func (o *RestColServiceGetCollectionOK) String() string {
	return fmt.Sprintf("[GET /v1/collections/{cid}][%d] restColServiceGetCollectionOK  %+v", 200, o.Payload)
}

func (o *RestColServiceGetCollectionOK) GetPayload() *models.APIGetCollectionResponse {
	return o.Payload
}

func (o *RestColServiceGetCollectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGetCollectionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestColServiceGetCollectionDefault creates a RestColServiceGetCollectionDefault with default headers values
func NewRestColServiceGetCollectionDefault(code int) *RestColServiceGetCollectionDefault {
	return &RestColServiceGetCollectionDefault{
		_statusCode: code,
	}
}

/*
RestColServiceGetCollectionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RestColServiceGetCollectionDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this rest col service get collection default response has a 2xx status code
func (o *RestColServiceGetCollectionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this rest col service get collection default response has a 3xx status code
func (o *RestColServiceGetCollectionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this rest col service get collection default response has a 4xx status code
func (o *RestColServiceGetCollectionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this rest col service get collection default response has a 5xx status code
func (o *RestColServiceGetCollectionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this rest col service get collection default response a status code equal to that given
func (o *RestColServiceGetCollectionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the rest col service get collection default response
func (o *RestColServiceGetCollectionDefault) Code() int {
	return o._statusCode
}

func (o *RestColServiceGetCollectionDefault) Error() string {
	return fmt.Sprintf("[GET /v1/collections/{cid}][%d] RestColService_GetCollection default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceGetCollectionDefault) String() string {
	return fmt.Sprintf("[GET /v1/collections/{cid}][%d] RestColService_GetCollection default  %+v", o._statusCode, o.Payload)
}

func (o *RestColServiceGetCollectionDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RestColServiceGetCollectionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
