// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRestColServiceGetCollection2Params creates a new RestColServiceGetCollection2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRestColServiceGetCollection2Params() *RestColServiceGetCollection2Params {
	return &RestColServiceGetCollection2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewRestColServiceGetCollection2ParamsWithTimeout creates a new RestColServiceGetCollection2Params object
// with the ability to set a timeout on a request.
func NewRestColServiceGetCollection2ParamsWithTimeout(timeout time.Duration) *RestColServiceGetCollection2Params {
	return &RestColServiceGetCollection2Params{
		timeout: timeout,
	}
}

// NewRestColServiceGetCollection2ParamsWithContext creates a new RestColServiceGetCollection2Params object
// with the ability to set a context for a request.
func NewRestColServiceGetCollection2ParamsWithContext(ctx context.Context) *RestColServiceGetCollection2Params {
	return &RestColServiceGetCollection2Params{
		Context: ctx,
	}
}

// NewRestColServiceGetCollection2ParamsWithHTTPClient creates a new RestColServiceGetCollection2Params object
// with the ability to set a custom HTTPClient for a request.
func NewRestColServiceGetCollection2ParamsWithHTTPClient(client *http.Client) *RestColServiceGetCollection2Params {
	return &RestColServiceGetCollection2Params{
		HTTPClient: client,
	}
}

/*
RestColServiceGetCollection2Params contains all the parameters to send to the API endpoint

	for the rest col service get collection2 operation.

	Typically these are written to a http.Request.
*/
type RestColServiceGetCollection2Params struct {

	// Cid.
	Cid string

	// Pid.
	Pid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rest col service get collection2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceGetCollection2Params) WithDefaults() *RestColServiceGetCollection2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rest col service get collection2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceGetCollection2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rest col service get collection2 params
func (o *RestColServiceGetCollection2Params) WithTimeout(timeout time.Duration) *RestColServiceGetCollection2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rest col service get collection2 params
func (o *RestColServiceGetCollection2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rest col service get collection2 params
func (o *RestColServiceGetCollection2Params) WithContext(ctx context.Context) *RestColServiceGetCollection2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rest col service get collection2 params
func (o *RestColServiceGetCollection2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rest col service get collection2 params
func (o *RestColServiceGetCollection2Params) WithHTTPClient(client *http.Client) *RestColServiceGetCollection2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rest col service get collection2 params
func (o *RestColServiceGetCollection2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCid adds the cid to the rest col service get collection2 params
func (o *RestColServiceGetCollection2Params) WithCid(cid string) *RestColServiceGetCollection2Params {
	o.SetCid(cid)
	return o
}

// SetCid adds the cid to the rest col service get collection2 params
func (o *RestColServiceGetCollection2Params) SetCid(cid string) {
	o.Cid = cid
}

// WithPid adds the pid to the rest col service get collection2 params
func (o *RestColServiceGetCollection2Params) WithPid(pid string) *RestColServiceGetCollection2Params {
	o.SetPid(pid)
	return o
}

// SetPid adds the pid to the rest col service get collection2 params
func (o *RestColServiceGetCollection2Params) SetPid(pid string) {
	o.Pid = pid
}

// WriteToRequest writes these params to a swagger request
func (o *RestColServiceGetCollection2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cid
	if err := r.SetPathParam("cid", o.Cid); err != nil {
		return err
	}

	// path param pid
	if err := r.SetPathParam("pid", o.Pid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
