// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRestColServiceListCollections2Params creates a new RestColServiceListCollections2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRestColServiceListCollections2Params() *RestColServiceListCollections2Params {
	return &RestColServiceListCollections2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewRestColServiceListCollections2ParamsWithTimeout creates a new RestColServiceListCollections2Params object
// with the ability to set a timeout on a request.
func NewRestColServiceListCollections2ParamsWithTimeout(timeout time.Duration) *RestColServiceListCollections2Params {
	return &RestColServiceListCollections2Params{
		timeout: timeout,
	}
}

// NewRestColServiceListCollections2ParamsWithContext creates a new RestColServiceListCollections2Params object
// with the ability to set a context for a request.
func NewRestColServiceListCollections2ParamsWithContext(ctx context.Context) *RestColServiceListCollections2Params {
	return &RestColServiceListCollections2Params{
		Context: ctx,
	}
}

// NewRestColServiceListCollections2ParamsWithHTTPClient creates a new RestColServiceListCollections2Params object
// with the ability to set a custom HTTPClient for a request.
func NewRestColServiceListCollections2ParamsWithHTTPClient(client *http.Client) *RestColServiceListCollections2Params {
	return &RestColServiceListCollections2Params{
		HTTPClient: client,
	}
}

/*
RestColServiceListCollections2Params contains all the parameters to send to the API endpoint

	for the rest col service list collections2 operation.

	Typically these are written to a http.Request.
*/
type RestColServiceListCollections2Params struct {

	// Pid.
	Pid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rest col service list collections2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceListCollections2Params) WithDefaults() *RestColServiceListCollections2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rest col service list collections2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceListCollections2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rest col service list collections2 params
func (o *RestColServiceListCollections2Params) WithTimeout(timeout time.Duration) *RestColServiceListCollections2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rest col service list collections2 params
func (o *RestColServiceListCollections2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rest col service list collections2 params
func (o *RestColServiceListCollections2Params) WithContext(ctx context.Context) *RestColServiceListCollections2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rest col service list collections2 params
func (o *RestColServiceListCollections2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rest col service list collections2 params
func (o *RestColServiceListCollections2Params) WithHTTPClient(client *http.Client) *RestColServiceListCollections2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rest col service list collections2 params
func (o *RestColServiceListCollections2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPid adds the pid to the rest col service list collections2 params
func (o *RestColServiceListCollections2Params) WithPid(pid string) *RestColServiceListCollections2Params {
	o.SetPid(pid)
	return o
}

// SetPid adds the pid to the rest col service list collections2 params
func (o *RestColServiceListCollections2Params) SetPid(pid string) {
	o.Pid = pid
}

// WriteToRequest writes these params to a swagger request
func (o *RestColServiceListCollections2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param pid
	if err := r.SetPathParam("pid", o.Pid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
