// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/restcol/api/go-openapiv2/models"
)

// NewRestColServiceCreateCollection2Params creates a new RestColServiceCreateCollection2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRestColServiceCreateCollection2Params() *RestColServiceCreateCollection2Params {
	return &RestColServiceCreateCollection2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewRestColServiceCreateCollection2ParamsWithTimeout creates a new RestColServiceCreateCollection2Params object
// with the ability to set a timeout on a request.
func NewRestColServiceCreateCollection2ParamsWithTimeout(timeout time.Duration) *RestColServiceCreateCollection2Params {
	return &RestColServiceCreateCollection2Params{
		timeout: timeout,
	}
}

// NewRestColServiceCreateCollection2ParamsWithContext creates a new RestColServiceCreateCollection2Params object
// with the ability to set a context for a request.
func NewRestColServiceCreateCollection2ParamsWithContext(ctx context.Context) *RestColServiceCreateCollection2Params {
	return &RestColServiceCreateCollection2Params{
		Context: ctx,
	}
}

// NewRestColServiceCreateCollection2ParamsWithHTTPClient creates a new RestColServiceCreateCollection2Params object
// with the ability to set a custom HTTPClient for a request.
func NewRestColServiceCreateCollection2ParamsWithHTTPClient(client *http.Client) *RestColServiceCreateCollection2Params {
	return &RestColServiceCreateCollection2Params{
		HTTPClient: client,
	}
}

/*
RestColServiceCreateCollection2Params contains all the parameters to send to the API endpoint

	for the rest col service create collection2 operation.

	Typically these are written to a http.Request.
*/
type RestColServiceCreateCollection2Params struct {

	// Body.
	Body *models.RestColServiceCreateCollectionBody

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rest col service create collection2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceCreateCollection2Params) WithDefaults() *RestColServiceCreateCollection2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rest col service create collection2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestColServiceCreateCollection2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) WithTimeout(timeout time.Duration) *RestColServiceCreateCollection2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) WithContext(ctx context.Context) *RestColServiceCreateCollection2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) WithHTTPClient(client *http.Client) *RestColServiceCreateCollection2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) WithBody(body *models.RestColServiceCreateCollectionBody) *RestColServiceCreateCollection2Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) SetBody(body *models.RestColServiceCreateCollectionBody) {
	o.Body = body
}

// WithProjectID adds the projectID to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) WithProjectID(projectID string) *RestColServiceCreateCollection2Params {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the rest col service create collection2 params
func (o *RestColServiceCreateCollection2Params) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *RestColServiceCreateCollection2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
